version: 1.0.{build}

environment:
  access_token:
    secure: uur3Y6W4UKOeKeIUFXCzs9l34yTk19NdrE/RojsviFtyj72W/2D3X/2SyB2QpY2d

install:
 - cmd: npm install

build_script:
 - cmd: node node_modules\typescript\bin\tsc
 - cmd: node node_modules\uglify-js\bin\uglifyjs --compress --mangle --output bin\HtmlPivotViewer.min.js -- bin\HtmlPivotViewer.js

deploy_script:
 - cmd: git config --global credential.helper store
 - cmd: echo https://%access_token%:x-oauth-basic@github.com > %USERPROFILE%\.git-credentials
 - cmd: git config --global user.email "mattleibow@live.com"
 - cmd: git config --global user.name "Matthew Leibowitz (CI)"

 - cmd: git clone -v --single-branch -b gh-pages https://github.com/mattleibow/HtmlPivotViewer.git gh-pages

 - cmd: if not exist gh-pages\bin\ mkdir gh-pages\bin\
 - cmd: if not exist gh-pages\css\ mkdir gh-pages\css\
 - cmd: if not exist gh-pages\cxml\ mkdir gh-pages\cxml\
 - cmd: copy /Y bin\*.min.js gh-pages\bin\
 - cmd: copy /Y css\* gh-pages\css\
 - cmd: copy /Y cxml\* gh-pages\cxml\
 - cmd: copy /Y index.html gh-pages\index.html

 - cmd: git --git-dir=gh-pages\.git --work-tree=gh-pages add .
 - cmd: git --git-dir=gh-pages\.git --work-tree=gh-pages commit -m "Build %APPVEYOR_BUILD_VERSION% for commit %APPVEYOR_REPO_COMMIT% by %APPVEYOR_REPO_COMMIT_AUTHOR%"
 - cmd: git --git-dir=gh-pages\.git --work-tree=gh-pages push origin gh-pages

artifacts:
 - path: bin\HtmlPivotViewer.min.js
 - path: bin\HtmlPivotViewer.js
